FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.11-bookworm-build

RUN install_packages ffmpeg v4l-utils libopenjp2-7

ENV UDEV=1

WORKDIR /usr/src/app

COPY app/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY app/ .

CMD ["python3", "server.py"]
